interactive mode and documentation for it

diff --git a/gpt b/gpt
--- a/gpt
+++ b/gpt
@@ -29,6 +29,33 @@ function appendConversation {
   fi
 }
 
+function sendMsg {
+  curl -s -X POST https://api.openai.com/v1/chat/completions \
+    -H 'Content-Type: application/json' \
+    -H "Authorization: Bearer $OPENAI_API_KEY" \
+    -d "{
+          \"model\": \"gpt-3.5-turbo\", 
+          \"messages\": [
+            $(cat $CONVO)
+          ] 
+        }"
+}
+
+function procOutput {
+
+  jqFilteredOutput=$(echo $@ | jq  '.choices[0].message.content')
+  jqFilteredOutput=$(echo $jqFilteredOutput | sed -E 's/"(.*)"/\1/g')
+
+  # Append user's input to the conversation ONLY IF we got good output.
+  if [ ! "$jqFilteredOutput" = 'null' ]; then
+    echo -e $jqFilteredOutput
+    appendConversation assistant $jqFilteredOutput
+  else
+    echo Error: $(echo $@ | jq '.error.message')
+    exit 1
+  fi
+}
+
 AUTOCOMPLETION_CMD='function gpt_convo_autocomplete {\n\tCOMPREPLY+=($(find ${HOME}/.gpt_convos/ -type f -name "${2}*" -exec basename {} \;))\n}\n\ncomplete -F gpt_convo_autocomplete gpt\n'
 
 which js >/dev/null
@@ -40,6 +67,7 @@ fi
 OPENAI_API_KEY=$(cat ${HOME}/Documents/GPT_KEY)
 GPT_DIR=$(dirname $0)
 CON_DIR=${HOME}/.gpt_convos
+IS_INTERACTIVE=false
 if [ ! -d $CON_DIR ]; then
   mkdir -p $CON_DIR
 fi
@@ -48,7 +76,7 @@ CONVO=$GPT_DIR/convo
 SYS_MSG=
 
 # Allow the user to resume any conversation.
-while getopts "gs:c:l" _opt; do
+while getopts "igs:c:l" _opt; do
   case $_opt in
     # Switch to another conversation. If it exists, we'll resume that one. 
     # Otherwise, it starts a new one.
@@ -65,7 +93,8 @@ while getopts "gs:c:l" _opt; do
     s) SYS_MSG="$OPTARG";;
     g) echo -e ${AUTOCOMPLETION_CMD}
        exit;;
-    *) echo $_opt is an invalid option. Exitting...\n
+    i) IS_INTERACTIVE=true;;
+    *) echo -e "$_opt is an invalid option. Exitting...\n"
        exit 1;;
   esac
 done
@@ -80,7 +109,7 @@ fi
 # Prevent sending ChatGPT empty messages.
 shift $((OPTIND - 1))
 input="$@"
-if [ $# -lt 1 -a -z "$SYS_MSG" ]; then
+if [ ! IS_INTERACTIVE -a $# -lt 1 -a -z "$SYS_MSG" ]; then
   echo "$0: I refuse to waste money by sending ChatGPT an empty message. Exitting..."
   exit 1
 fi
@@ -90,24 +119,11 @@ appendConversation system $SYS_MSG
 appendConversation user ${input}
 
 # Send the message!
-output=$(curl -s -X POST https://api.openai.com/v1/chat/completions \
-  -H 'Content-Type: application/json' \
-  -H "Authorization: Bearer $OPENAI_API_KEY" \
-  -d "{
-        \"model\": \"gpt-3.5-turbo\", 
-        \"messages\": [
-        $(cat $CONVO)
-        ] 
-      }")
-
-jqFilteredOutput=$(echo $output | jq  '.choices[0].message.content')
-jqFilteredOutput=$(echo $jqFilteredOutput | sed -E 's/"(.*)"/\1/g')
-
-# Append user's input to the conversation ONLY IF we got good output.
-if [ ! "$jqFilteredOutput" = 'null' ]; then
-  echo -e $jqFilteredOutput
-  appendConversation assistant $jqFilteredOutput
-else
-  echo Error: $(echo $output | jq '.error.message')
-  exit 1
+if $IS_INTERACTIVE; then
+  while true; do
+    echo -ne '\e[1;32m[You]:\e[m '; read newMsg
+    appendConversation user $newMsg
+    output=$(sendMsg)
+    echo -ne '\e[1;34m[GPT]:\e[m '; procOutput "$output"
+  done
 fi
